Update user-manual-schlafen-die-zweite.md
Schlaue-Lise-IT-Project/schlaue-lise pull request #3
Opened 2021-11-19 14:12 UTC by Sebastian-Klement

Gönn dir 💯

2021-11-20 16:54 UTC, noopliez requested changes
Nochmal main in den branch mergen (siehe Kommentar)

2021-11-22 08:26 UTC, noopliez commented on user-manual.md
> +Die Funktion "Hygieneartikel" ist total großartig. Hier kann der Anwender beliebige Hygieneartikel anfragen und bekommt die entsprechenden Ausgabestellen angezeigt. Diese sind wieder mit einem `Deep
> Die Funktion "Hygieneartikel" ist total großartig.

Soll das so sein?

2021-11-22 08:34 UTC, noopliez commented on user-manual.md
> +##### Zusammenfassug Beispiel 2:
```suggestion
##### Zusammenfassung Beispiel 2:
```

2021-11-22 08:38 UTC, noopliez commented on user-manual.md
> +In diesem Beispiel sucht ein Erwachsener Mensch eine längerfristige Unterkunft. Er nimmt keine Drogen und hat kein Haustier. Der Endpunkt ist eine Auflistung von Unterkünften die Erwachsene aufnehmen
```suggestion
In diesem Beispiel sucht ein Erwachsener eine längerfristige Unterkunft. Er nimmt keine Drogen und hat kein Haustier. Der Endpunkt ist eine Auflistung von Einrichtungen, die Unterstützung bei der Suche nach einer längerfristigen Unterkunft für Erwachsene anbieten.
```

2021-11-22 08:38 UTC, noopliez commented on user-manual.md
> +Die gesamte Kommunikation findet in deutscher Sprache statt. Während der Entwicklung wurde großen Wert darauf gelegt, den Einstieg in die Kommunikation mit der Anwendung sehr niederschwellig zu gesta
```suggestion
Die gesamte Kommunikation findet in deutscher Sprache statt. Während der Entwicklung wurde großen Wert darauf gelegt, den Einstieg in die Kommunikation mit der Anwendung sehr niederschwellig zu gestallten. So spielt es beispielsweise keine Rolle, ob eine Kommunikation mit einem Halbsatz oder sogar nur mit einem Wort beginnt. Am Ende und nach erfolgreicher Eingabe aller benötigten Informationen, wird der nutzenden Person eine Liste mit Einrichtungen angezeigt, die in der jeweiligen Situation der Anwender:innen hilfreich sein könnten.
```

2021-11-22 08:39 UTC, noopliez commented on user-manual.md
>  #### Beispiel 2 "Langfristig Jugendlicher":
```suggestion
#### Beispiel 2 "Langfristig für Jugendliche":
```

2021-11-22 08:40 UTC, noopliez commented on user-manual.md
> +In diesem Beispiel sucht ein Jugendlicher eine längerfristige Unterkunft. Er nimmt keine Drogen und hat kein Haustier. Der Endpunkt ist eine Auflistung von Unterkünften die Jugendliche aufnehmen.
```suggestion
In diesem Beispiel sucht eine Jugendliche eine längerfristige Unterkunft. Sie nimmt keine Drogen und hat kein Haustier. Der Endpunkt ist eine Auflistung von Einrichtungen, die Unterstützung bei der Suche nach einer längerfristigen Unterkunft für Jugendliche anbieten.
```

2021-11-22 08:42 UTC, noopliez commented on user-manual.md
> +In diesem Beispiel sucht ein erwachener Mann eine Notunterkunft. Er nimmt keine Drogen und hat kein Haustier. Der Endpunkt ist eine Auflistung von Notunterkünften die nur Männer ohne Haustier und ohn
```suggestion
In diesem Beispiel sucht ein junger Erwachsener eine Notunterkunft. Er nimmt keine Drogen und hat kein Haustier. Der Endpunkt ist eine Auflistung von Notunterkünften die nur Männer ohne Haustier und ohne Drogenprobleme aufnehmen.
```

2021-11-22 08:42 UTC, noopliez commented on user-manual.md
> +In diesem Beispiel sucht eine erwachene Frau eine Notunterkunft. Sie nimmt keine Drogen und hat kein Haustier. Der Endpunkt ist eine Auflistung von Notunterkünften die nur Frauen ohne Haustier und oh
```suggestion
In diesem Beispiel sucht eine erwachsene Frau eine Notunterkunft. Sie nimmt keine Drogen und hat kein Haustier. Der Endpunkt ist eine Auflistung von Notunterkünften die nur Frauen ohne Haustier und ohne Drogenprobleme aufnehmen.
```

2021-11-22 08:44 UTC, noopliez commented on user-manual.md
> +In diesem Beispiel sucht eine erwachener Non-Binärer Mensch eine Notunterkunft. Dieser nimmt keine Drogen und hat kein Haustier. Der Endpunkt ist eine Auflistung von allen Notunterkünften die Frauen
```suggestion
In diesem Beispiel sucht eine erwachsener non-binärer Mensch eine Notunterkunft. Dieser nimmt keine Drogen und hat kein Haustier. Der Endpunkt ist eine Auflistung von allen Notunterkünften die Frauen und Männer ohne Haustier und ohne Drogenprobleme aufnehmen. Da es zum Zeitpunkt der Entwicklung des Prototyps keine Unterkunft für non-binäre Menschen gab, wird auf beide Unterkunftarten verwiesen.
```

2021-11-22 08:46 UTC, noopliez commented on user-manual.md
> +In diesem Beispiel sucht eine Jugendlicher eine Notunterkunft. Er nimmt keine Drogen und hat kein Haustier. Das Geschlecht spielt keine Rolle für die selektion der Unterkünfte. Der Endpunkt ist eine
```suggestion
In diesem Beispiel sucht ein non-binärer Jugendlicher eine Notunterkunft. Er nimmt keine Drogen und hat kein Haustier. Das Geschlecht spielt keine Rolle für die Auswahl der Unterkünfte, da es in Nürnberg nur danach geht, ob der Mensch jugendlich ist oder nicht. Der Endpunkt ist eine Auflistung von Notunterkünften die nur Jugendliche ohne Haustier und ohne Drogenprobleme aufnehmen.
```

2021-11-22 08:48 UTC, noopliez commented on user-manual.md
> +In diesem Beispiel sucht ein erwachener Mann eine Notunterkunft. Er nimmt keine Drogen und hat jedoch ein Haustier. Der Endpunkt ist eine Auflistung von Notunterkünften die Menschen mit Haustier und
```suggestion
In diesem Beispiel sucht ein erwachsener Mann eine Notunterkunft. Er nimmt keine Drogen, hat jedoch ein Haustier. Der Endpunkt ist eine Auflistung von Notunterkünften die Menschen mit Haustier und ohne Drogenprobleme aufnehmen. Hat ein Hilfesuchender ein Haustier und ein Drogenproblem wird bei der Auswahl der Notunterkünfte das Haustier priorisiert. Auch das Alter spielt keine Rolle. 
```

2021-11-22 08:49 UTC, noopliez commented on user-manual.md
> +In diesem Beispiel sucht ein erwachener Mann eine Notunterkunft. Er nimmt Drogen und hat kein Haustier. Der Endpunkt ist eine Auflistung von Notunterkünften die Menschen ohne Haustier aber mit Drogen
```suggestion
In diesem Beispiel sucht ein erwachsener Mann eine Notunterkunft. Er nimmt Drogen und hat kein Haustier. Der Endpunkt ist eine Auflistung von Notunterkünften die Menschen ohne Haustier aber mit Drogenproblemen aufnehmen. Hat ein Hilfesuchender ein Haustier und ein Drogenproblem wird bei der Auswahl der Notunterkünfte das Haustier priorisiert. 
```

2021-11-22 08:50 UTC, noopliez requested changes
- [x] Siehe Comments

2021-11-23 05:55 UTC, Sebastian-Klement reviewed
So machen wir das. Den Satz in Hygiene wird bearbeitet sobald ich das "Hallo" in den Beispielkonversationen entferne.

2021-11-23 07:42 UTC, noopliez approved these changes
Kann gemerged werden

2021-11-23 07:42 UTC, noopliez commented on user-manual.md
> +##### Zusammenfassug Beispiel 1:
```suggestion
##### Zusammenfassung Beispiel 1:
```

2021-11-23 07:44 UTC, merged