danke in rules angelegt und responses_main sowie nlu_main erweitert
Schlaue-Lise-IT-Project/schlaue-lise pull request #49
Opened 2021-11-26 06:43 UTC by Sebastian-Klement

Ich kann das leider in VSC nicht testen. Bitte Feedback oder wenn das nichts war einfach wieder löschen :D

2021-11-26 07:27 UTC, noopliez requested changes

2021-11-26 07:27 UTC, noopliez commented on data/nlu/responses/responses_main.yml
> +    - text: "Bitte. Ich freue mich, dass ich dir helfen konnte."
> Bitte. Ich freue mich, dass ich dir helfen konnte.

Find ich irgendwie komisch die Formulierung. Hab aber auch grad keine bessere

2021-11-26 07:27 UTC, noopliez commented on data/rules/rules_main.yml
> +  - rule: bedanken
```suggestion
  - rule: Auf Danke entsprechend reagieren
```

2021-11-26 09:20 UTC, noopliez commented on data/nlu/responses/responses_main.yml
> +    - text: "Bitte. Ich freue mich, dass ich dir helfen konnte."
@Pusteblum3 @MarieConstantin @Lena-Holderrieth hat da von euch jmd eine Idee?

2021-11-26 12:49 UTC, Lena-Holderrieth commented on data/nlu/responses/responses_main.yml
> +    - text: "Bitte. Ich freue mich, dass ich dir helfen konnte."
"Bitte."
"Gerne."
"Gerne. Kann ich sonst noch etwas für dich tun?"

Das sind meine Vorschläge

2021-11-26 12:56 UTC, noopliez commented on data/nlu/responses/responses_main.yml
> +    - text: "Bitte. Ich freue mich, dass ich dir helfen konnte."
> "Gerne. Kann ich sonst noch etwas für dich tun?"

Das find ich gut

2021-11-29 07:51 UTC, noopliez commented on data/nlu/responses/responses_main.yml
> +    - text: "Bitte. Ich freue mich, dass ich dir helfen konnte."
```suggestion
    - text: "Gerne. Kann ich sonst noch etwas für dich tun?"
```

2021-11-29 07:53 UTC, noopliez requested changes

2021-11-29 07:53 UTC, noopliez commented on data/nlu/nlu_main.yml
> +  - intent: bedanken
```suggestion
  - intent: danke
```

2021-11-29 07:54 UTC, noopliez approved these changes

2021-11-29 07:54 UTC, merged